services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: ${IMAGE_NAME}

  modeeb:
    image: mongo
    container_name: modeeb
    volumes:
      - ./assets/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    env_file: ${ENV_FILE}

  jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - ${COM_HOST}:8080
    env_file: ${ENV_FILE}
    command: /bin/server jmjanzen.com

  api.jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - modeeb
      - server
    ports:
      - ${API_HOST}:8181
    env_file: ${ENV_FILE}
    command: /bin/server api.jmjanzen.com


  jmjanzen.cv:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - ${CV_HOST}:8282
    env_file: ${ENV_FILE}
    command: /bin/server jmjanzen.cv

  blog.jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - ${BLOG_HOST}:8383
    env_file: ${ENV_FILE}
    command: /bin/server blog.jmjanzen.com
