services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: ${IMAGE_NAME}

  modeeb:
    image: mongo
    container_name: modeeb
    volumes:
      - ./assets/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    env_file: ${ENV_FILE}

  jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - 127.0.0.1:${COM_PORT}:${COM_PORT}
    env_file: ${ENV_FILE}
    command: /bin/server jmjanzen.com

  api.jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - modeeb
      - server
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
    env_file: ${ENV_FILE}
    command: /bin/server api.jmjanzen.com


  jmjanzen.cv:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - 127.0.0.1:${CV_PORT}:${CV_PORT}
    env_file: ${ENV_FILE}
    command: /bin/server jmjanzen.cv

  blog.jmjanzen.com:
    image: ${IMAGE_NAME}
    depends_on:
      - server
    ports:
      - 127.0.0.1:${BLOG_PORT}:${BLOG_PORT}
    env_file: ${ENV_FILE}
    command: /bin/server blog.jmjanzen.com
