#!/usr/bin/env -S bash

source "${ENV_FILE:-.env}"

if [ "$(git status --porcelain)" ]
then
    read -n 1 -p "Uncommitted changes -- continue anyway (y/N)? " answer
    [[ -z "$answer" || "$answer" == "n" ]] && exit 1
fi

docker compose build server
