#!/usr/bin/env -S bash

source ./.env

if [ "$(git status --porcelain)" ]
then
    read -n 1 -p "Uncommitted changes -- continue anyway (y/N)? " answer
    [[ -z "$answer" || "$answer" == "n" ]] && exit 1
fi

docker save jm-server:latest | gzip | ssh $REMOTE_HOST docker load

ssh -t $REMOTE_HOST <<MEOW
cd $REMOTE_DIR
docker compose up -d
MEOW

