#!/usr/bin/env -S bash

if [[ $# -lt 1 ]]
then
    echo 'Usage: ./scripts/update-modeed <mongodb-seed-file>'
    exit 1
fi

source "${ENV_FILE:-.env}"

rsync -v "$1" ${REMOTE_HOST}:${REMOTE_DIR}/assets/

DOCKER_HOST="ssh://${REMOTE_HOST}" docker compose --env-file ${ENV_FILE} down -v modeeb
DOCKER_HOST="ssh://${REMOTE_HOST}" docker compose --env-file ${ENV_FILE} up -d modeeb
