definitions:
  interests.Interest:
    properties:
      aliases:
        items:
          type: string
        type: array
      elaborationUrl:
        type: string
      name:
        type: string
      passion:
        type: number
      slug:
        type: string
      summary:
        type: string
    type: object
  modes.Error:
    properties:
      message:
        type: string
    type: object
  modes.Mode:
    properties:
      data:
        additionalProperties: {}
        type: object
      id:
        type: integer
      mode:
        type: string
    type: object
  modes.NotFound:
    properties:
      message:
        type: string
    type: object
  tils.Til:
    properties:
      name:
        type: string
      slug:
        type: string
      summary:
        type: string
    type: object
info:
  contact: {}
paths:
  /interests:
    get:
      description: get a JSON array of strings
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get all interests
  /interests/{slug}:
    get:
      description: get interest, based on provided slug
      parameters:
      - description: slug of specific interest
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interests.Interest'
      summary: Get interest
  /modes/{id}:
    get:
      description: get a representation of my mode by mode id
      parameters:
      - description: which mode
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modes.Mode'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/modes.NotFound'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/modes.Error'
      summary: Get my modes
  /tils:
    get:
      description: get a JSON array of strings
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get all tils
  /tils/{slug}:
    get:
      description: get til, based on provided slug
      parameters:
      - description: slug of specific til
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tils.Til'
      summary: Get til
swagger: "2.0"
