definitions:
  me.Error:
    properties:
      message:
        type: string
    type: object
  me.Me:
    properties:
      id:
        type: integer
      mode:
        type: string
      name:
        $ref: '#/definitions/me.Name'
    type: object
  me.Name:
    properties:
      first:
        type: string
      last:
        type: string
      nick:
        type: string
    type: object
  me.NotFound:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /me/{id}:
    get:
      description: get a representation of me by mode id
      parameters:
      - description: which mode
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/me.Me'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/me.NotFound'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/me.Error'
      summary: Get me
swagger: "2.0"
